name: playground
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dls_thoughtworks:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  #Todo: Add fonts & styles here
  fonts:
    - family: Poppins
      fonts:
        - asset: packages/dls_thoughtworks/foundation/typography/fonts/Poppins-Regular.ttf
        - asset: packages/dls_thoughtworks/foundation/typography/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: packages/dls_thoughtworks/foundation/typography/fonts/Poppins-Bold.ttf
          weight: 700
