name: dls_thoughtworks
description: A Design System package.
version: 0.0.1
homepage: ''

environment:
  sdk: '>=2.19.1 <=3.7.1'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/
    - assets/icons/
    - lib/foundation/typography/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/foundation/typography/fonts/Poppins-Regular.ttf
        - asset: lib/foundation/typography/fonts/Poppins-Medium.ttf
          weight: 700
