name: todo
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  
  intl: ^0.18.1


  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true
